name: displacement-chapter-replication

channels:
  - udst  # for pandana
  - conda-forge  # for geopandas

dependencies:
  - python=3.5
  - geopandas
  - jupyter
  - matplotlib
  - numpy
  - pandana
  - pandas
  - statsmodels
